[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Findaaron <aarondean86@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris = "0.2.0"
